# Generated by Django 5.0.7 on 2024-11-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='f_name',
            new_name='name',
        ),
    ]
