# Generated by Django 5.0.7 on 2024-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subjet',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
