# Generated by Django 5.0.7 on 2024-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_message_email_alter_message_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='meals')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
